/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpcxat.h"
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <stdio.h>

#define MAX_BUFFER 500

void * send_msg_1_svc(char **argp, struct svc_req *rqstp){
	static char * result;
	int fitxer;

	xdr_free((xdrproc_t)xdr_string, (char *)&result);

	fitxer = open("msgDB.txt", O_WRONLY | O_APPEND | O_CREAT, 0666);

	//write(1, *argp, strlen(*argp));
	write(fitxer, *argp, strlen(*argp));
	
	close(fitxer);

	return (void *) &result;
}

char ** get_msg_1_svc(int *argp, struct svc_req *rqstp){
	static char * result = NULL;
	FILE *fp;
	char buff[MAX_BUFFER];
	
	xdr_free((xdrproc_t)xdr_string, (char *)&result);

	/*
	* Popen internament fa un fork, obre una pipe i execl de la comanda que li passem
	* Compta la quantitat de linies que conté el fitxer
	*/
	if ((fp = popen("wc -l msgDB.txt | awk '{print $1}'", "r")) == NULL) {
        printf("Error opening pipe!\n");
		exit(-1);
    }

	fgets(buff, MAX_BUFFER, fp);
	
	pclose(fp);

	if(*argp <= atoi(buff)){
		//Demanem 1 missatge
		//Amb tail -n +x file em mostra des de la linia x fins final de fitxer, però
		//afegim head per acotar-ho a un missagte
		int x1 = *argp;
		int x2 = 1;
		sprintf(buff, "tail -n +%d msgDB.txt | head -n %d", x1, x2);
		if ((fp = popen(buff, "r")) == NULL) {
			printf("Error opening pipe!\n");
			exit(-1);
		}

		memset(buff, '\0', MAX_BUFFER);

		fgets(buff, MAX_BUFFER, fp);
		pclose(fp);

		result = (char *)malloc(sizeof(char)*(strlen(buff) + 1));
		memset(result, '\0', strlen(buff) + 1);

		strcpy(result, buff);
	}

	return &result;
}

