/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpcxat.h"
#include <unistd.h>
#include <signal.h>
#include <pthread.h>

char * send_msg_1_arg;

void signal_handler(int signum){
	
	switch(signum){
		case SIGINT:
			free(send_msg_1_arg);
			exit(0);
			break;
		default:
			break;

	}
	
	//Reasignar el signal simplement per bona praxi, però no cal en aquest cas
	signal(SIGINT, signal_handler);
}

void * pollingMsg(void *host){
	char *hostname = (char *) host;
	CLIENT *clnt;
	char **result_2;
	int  get_msg_1_arg;

	clnt = clnt_create (host, RPC_XAT, NAKO, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
	
	while(1){
		get_msg_1_arg = 0;
		result_2 = get_msg_1(&get_msg_1_arg, clnt);
		write(1, *result_2, strlen(*result_2));
		write(1, "\n", 1);

		//printf("- %s", *result_2);
	
		if (result_2 == (char **) NULL) {
			clnt_perror (clnt, "call failed");
		}

		sleep(5);
	}
	
	return NULL;
}

void rpc_xat_1(char *host){
	CLIENT *clnt;
	void  *result_1;
	char missatge[500];

#ifndef	DEBUG
	clnt = clnt_create (host, RPC_XAT, NAKO, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	signal(SIGINT, signal_handler);

	send_msg_1_arg = (char *)malloc(sizeof(char)*1);

	while(1){

		memset(missatge, '\0', 500);
		//Llegim del terminal
		int nBytes = read(0, missatge, sizeof(missatge));
		//missatge[nBytes - 1] = '\0';

		//Demanem memòria dinàmica per la trama que enviem
		send_msg_1_arg = (char *)realloc(send_msg_1_arg, sizeof(char)*nBytes);
		strcpy(send_msg_1_arg, missatge);

		//Enviar missatge al servidor
		result_1 = send_msg_1(&send_msg_1_arg, clnt);

		//Control d'error d'enviament
		if (result_1 == (void *) NULL) {
			clnt_perror (clnt, "call failed");
		}
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int main (int argc, char *argv[]){
	char *host;
	pthread_t idThread;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	signal(SIGINT, signal_handler);

	pthread_create(&idThread, NULL, &pollingMsg, host);
	rpc_xat_1 (host);
	pthread_join(idThread, NULL);
	exit (0);
}
