/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpcxat.h"
#include <unistd.h>

void * send_msg_1_svc(char **argp, struct svc_req *rqstp){
	static char * result;

	write(1, *argp, strlen(*argp));

	return (void *) &result;
}

char ** get_msg_1_svc(int *argp, struct svc_req *rqstp){
	static char * result;

	/*
	 * insert server code here
	 */

	return &result;
}

