/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpcxat.h"
#include <unistd.h>
#include <signal.h>

char * send_msg_1_arg;

void signal_handler(int signum){
	
	switch(signum){
		case SIGINT:
			free(send_msg_1_arg);
			exit(0);
			break;
		default:
			break;

	}
	
	//Reasignar el signal simplement per bona praxi, però no cal en aquest cas
	signal(SIGINT, signal_handler);
}

void rpc_xat_1(char *host){
	CLIENT *clnt;
	void  *result_1;

	char * *result_2;
	int  get_msg_1_arg;
	char missatge[500];

#ifndef	DEBUG
	clnt = clnt_create (host, RPC_XAT, NAKO, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	signal(SIGINT, signal_handler);

	send_msg_1_arg = (char *)malloc(sizeof(char)*1);
	
	while(1){

		memset(missatge, '\0', 500);
		//Llegim del terminal
		int nBytes = read(0, missatge, sizeof(missatge));
		//missatge[nBytes - 1] = '\0';

		//Demanem memòria dinàmica per la trama que enviem
		send_msg_1_arg = (char *)realloc(send_msg_1_arg, sizeof(char)*nBytes);
		strcpy(send_msg_1_arg, missatge);

		//Enviar missatge al servidor
		result_1 = send_msg_1(&send_msg_1_arg, clnt);
	}

	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = get_msg_1(&get_msg_1_arg, clnt);
	if (result_2 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int main (int argc, char *argv[]){
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	signal(SIGINT, signal_handler);

	rpc_xat_1 (host);
	exit (0);
}
