/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPCXAT_H_RPCGEN
#define _RPCXAT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define RPC_XAT 0x180601
#define NAKO 1

#if defined(__STDC__) || defined(__cplusplus)
#define send_msg 1
extern  void * send_msg_1(char **, CLIENT *);
extern  void * send_msg_1_svc(char **, struct svc_req *);
#define get_msg 1
extern  char ** get_msg_1(int *, CLIENT *);
extern  char ** get_msg_1_svc(int *, struct svc_req *);
extern int rpc_xat_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define send_msg 1
extern  void * send_msg_1();
extern  void * send_msg_1_svc();
#define get_msg 1
extern  char ** get_msg_1();
extern  char ** get_msg_1_svc();
extern int rpc_xat_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPCXAT_H_RPCGEN */
